### PR TITLE
Fix variable reference.

### PR DESCRIPTION
**Pull request by jbrown**

### CODE REVIEW

**Comment by achambers** [comment]
Thanks Justin.  There is already a PR for this (#34), although I'm waiting on tests.  Happy to merge yours, however, can you please add test as well?  I obviously missed something here so thanks for catching it for me :)

**Comment by achambers** [comment]
Hey dude.  How's it going? Any chance you could rebase this against master and I'll merge it in.  Having been overseas for the last 4.5 weeks, haven't had a chance to work on the asset adapter which was going to implicitly fix this.  Happy to merge yours in for now if you like.

**Comment by thehydroimpulse** [comment]
Any chance this can be resolved pretty soon?

**Comment by achambers** [comment]
Merged in https://github.com/achambers/ember-cli-deploy/commit/f12c4bc0a82084314f99d19b4aa8949504aee1e8

**Comment by bartj3** [comment]
The error is no longer raised but it now returns `Upload failed: undefined` for each failing upload?

**Comment by Dhaulagiri** [comment]
Same here

**Pull request closed without merging**
