### PR TITLE
Fixes error callback when uploading assets

### PR DESCRIPTION
**Pull request by house9**
- Error handling would result in the error 'uploadedFilePath is not defined'

### CODE REVIEW

**Comment by achambers** [comment]
Thanks @house9. There is obviously a test I missed here. Can you please write the failing test as a part of this PR so that we can be sure it's fixed?

**Comment by house9** [comment]
I need a pointer in the right direction :( - what is the best way to force the `MockS3Uploader.uploadFile` to fire the promises error handler?

**Comment by achambers** [comment]
@house9 The way I've been doing it (which isn't necessarily the best way but I'll fix that later) is to add a method on the mock object to tell it to resolve/reject the function.  Have a look at the `mock-s3-client` as an example.

**Comment by achambers** [comment]
Hi @house9.  Are you planning on writing some tests for this PR or shall I close it.  This is all going to change in the next release anyway, but I'm happy to merge your PR in if you add some tests to it.

**Comment by house9** [comment]
@achambers - test coverage added; sorry for the delay.

**Comment by achambers** [comment]
Sorry mate, have already started adding the asset adapter for v0.0.6 so this bug will no longer exist.  Plus I'd need you to re-raise the PR against the `next-release-v0.0.6` branch anyway and a lot has changed.  So I'm going to close this PR now.  Thanks for contributing mate.  Looking forward to seeing more contributions form you in the future

**Comment by house9** [comment]
:+1:

**Pull request closed without merging**
