### PR TITLE
Fixes README that broke as part of PR#29

### PR DESCRIPTION
**Pull request by jhuckabee**
Fixes the bug I introduced in the README in Pull Request #29.

Sorry about that.

### CODE REVIEW

**Comment by achambers** [comment]
Bugger. I missed that as well ;) Thanks

**Comment by achambers** [comment]
@jhuckabee, are you using this in any anger at the moment? If so, I'd love to talk about how and maybe discuss my plans for it and anything you think may be of value to add.

**Comment by jhuckabee** [comment]
@achambers would love to discuss your plans here.

We are not serving our index file from Redis, and instead are just timestamping the index file during the build and updating a CloudFront distribution's root document to reflect this new index after assets are synced. So in our case we just upload everything to S3 and hence PR #29.

I am curious about these various "adapter" issues, specifically #8. If deploying the index file to Redis is pulled out into an adapter, theoretically, we could add our own adapter that publishes the index file in whatever way we so choose?

Again, would love to discuss further.

**Comment by achambers** [comment]
Okie doke. 

As per the adapters, that's exactly the point. I want to provide a few but ultimately, once that ability is in, any one will be able to create their own adapter for any service they want to store their index file or assets. That's the goal anyway. 

I you use this manually it as a part of an automated build?

**Comment by jhuckabee** [comment]
Right now we're integrating the various deployment processes (all Ember CLI commands) via Grunt. I am curious about how other people are attacking this. Initially I thought some sort of ember cli command chaining mechanism could prove useful, but for expediency decided just to package it up with Grunt.

Let me know if I can help with this adapter refactor. Right now I have two additional addons that support the `deploy:assets` task that I could condense into a single index adapter.

**Comment by achambers** [comment]
Thanks mate

**Pull request merged**
