### PR TITLE
Add asset url rewriting to readme. Fixes #48.

### LINKED ISSUE #48: Asset url rewriting
I was able to successfully deploy index to a fuzzy-wookie server and my assets to S3. But shouldn't the asset urls in index be rewritten to point to S3? Am I missing something?

### PR DESCRIPTION
**Pull request by tomclose**
Fixes #48

### CODE REVIEW

**Comment by achambers** [comment]
Thanks for this Tom.  Any chance you could please rebase against master?  I'll then be happy to merge.

**Comment by tomclose** [comment]
Done.

**Comment by tomclose** [comment]
Are you still intending to merge this? I did the rebase.

**Comment by achambers** [comment]
Yes mate. Have been in Oz for the past 5 weeks. Got back to London last
night. Will get to it shortly.

**Comment by achambers** [comment]
Merged in https://github.com/achambers/ember-cli-deploy/commit/47ffd0cb5c881ba3cce2c7f9c2dc4b8a7a568ca6

**Pull request closed without merging**
